version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./client/:/app
      - /app/node_modules
  node-app:
    image: node-app
    env_file: ./server/.env
    ports:
      - "3001:3001"
    networks:
      - mern-app
    volumes:
      - ./server/:/app
      - /app/node_modules
networks:
  mern-app:
    driver: bridge
